from __future__ import annotations

import hashlib
import json
import re
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable

from mtg_parser.card import Card

from .models import DeckConfig, DeckMetadata


SECTION_ORDER = (
    "commander",
    "companion",
    "sideboard",
    "maybeboard",
    "creature",
    "artifact",
    "enchantment",
    "instant",
    "sorcery",
    "land",
)


def utc_now() -> datetime:
    return datetime.now(timezone.utc)


def timestamp(value: datetime) -> str:
    return value.astimezone(timezone.utc).strftime("%Y%m%dT%H%M%SZ")


def _safe_tag(tag: str) -> str:
    value = re.sub(r"[^a-zA-Z0-9_-]+", "-", tag.strip().lower()).strip("-")
    return value or "tag"


def _section(card: Card) -> str:
    tags = {str(tag).lower() for tag in card.tags}
    for candidate in SECTION_ORDER:
        if candidate in tags:
            return candidate
    return sorted(tags)[0] if tags else "uncategorized"


def render_body(cards: Iterable[Card]) -> str:
    grouped: dict[str, list[Card]] = defaultdict(list)
    for card in cards:
        grouped[_section(card)].append(card)

    order = {name: index for index, name in enumerate(SECTION_ORDER)}
    section_names = sorted(grouped, key=lambda name: (order.get(name, 100), name))
    lines: list[str] = []
    for index, section in enumerate(section_names):
        if index:
            lines.append("")
        lines.append(f"// {section.title()}")
        for card in sorted(
            grouped[section],
            key=lambda item: (
                item.name.lower(),
                item.extension or "",
                item.number or "",
                sorted(item.tags),
            ),
        ):
            line = f"{card.quantity} {card.name}"
            if card.extension:
                line += f" ({card.extension})"
            if card.number:
                line += f" {card.number}"
            line += "".join(f" #{_safe_tag(tag)}" for tag in sorted(card.tags))
            lines.append(line)

    return "\n".join(lines) + "\n"


def deck_hash(body: str) -> str:
    return hashlib.sha256(body.encode("utf-8")).hexdigest()


def _header(
    config: DeckConfig,
    retrieved_at: datetime,
    version: str,
    body: str,
    metadata: DeckMetadata | None,
) -> str:
    card_count = sum(
        int(match.group("quantity"))
        for match in re.finditer(r"^(?P<quantity>\d+) ", body, re.MULTILINE)
    )
    source_name = metadata.name if metadata else config.display_name
    return "\n".join(
        [
            "# Challenge32 synchronized decklist",
            f"# Deck: {source_name}",
            f"# Source: {config.source}",
            f"# URL: {config.url}",
            f"# Retrieved: {retrieved_at.astimezone(timezone.utc).isoformat()}",
            f"# Version: {version}",
            f"# Deck hash: sha256:{deck_hash(body)}",
            f"# Cards: {card_count}",
            "# Generated file; put analysis in notes/.",
            "",
        ]
    )


def _note_hashes(notes_dir: Path) -> set[str]:
    hashes: set[str] = set()
    if not notes_dir.exists():
        return hashes
    for path in notes_dir.glob("*.md"):
        if path.name == "status.md":
            continue
        try:
            content = path.read_text(encoding="utf-8")
        except OSError:
            continue
        hashes.update(re.findall(r"deck_hash:\s*(?:sha256:)?([0-9a-f]{64})", content, re.I))
    return hashes


def write_status(config: DeckConfig, state: dict[str, Any]) -> None:
    notes_dir = config.directory / "notes"
    notes_dir.mkdir(parents=True, exist_ok=True)
    current_hash = str(state["current_hash"]).removeprefix("sha256:")
    covered = current_hash in _note_hashes(notes_dir)
    status = "covered by analysis" if covered else "deck changed since the latest matching analysis"
    status_path = notes_dir / "status.md"
    status_path.write_text(
        "\n".join(
            [
                "# Analysis status",
                "",
                "This file is generated by `challenge32`; do not put analysis prose here.",
                "",
                f"- Deck: `{config.display_name}`",
                f"- Current version: `{state['current_version']}`",
                f"- Current hash: `sha256:{current_hash}`",
                f"- Status: **{status}**",
                "",
                "For a matching analysis note, include `deck_hash: sha256:<64-hex-digits>` in its front matter.",
                "",
            ]
        ),
        encoding="utf-8",
    )


def synchronize(
    config: DeckConfig,
    cards: Iterable[Card],
    metadata: DeckMetadata | None = None,
    retrieved_at: datetime | None = None,
    dry_run: bool = False,
) -> dict[str, Any]:
    retrieved_at = retrieved_at or utc_now()
    cards = list(cards)
    if not cards:
        raise ValueError("Refusing to synchronize an empty deck")
    if any(card.quantity <= 0 or not card.name.strip() for card in cards):
        raise ValueError("Refusing to synchronize cards with invalid names or quantities")

    body = render_body(cards)
    current_hash = deck_hash(body)
    state_path = config.directory / "state.json"
    old_state = json.loads(state_path.read_text(encoding="utf-8")) if state_path.exists() else None

    if old_state and old_state.get("current_hash") == f"sha256:{current_hash}":
        write_status(config, old_state) if not dry_run else None
        return {"changed": False, "version": old_state["current_version"], "hash": current_hash}

    version = f"{timestamp(retrieved_at)}--{current_hash[:7]}"
    state = {
        "deck": config.slug,
        "display_name": config.display_name,
        "source": config.source,
        "url": config.url,
        "color_identity": config.color_identity,
        "current_version": version,
        "current_hash": f"sha256:{current_hash}",
        "retrieved_at": retrieved_at.astimezone(timezone.utc).isoformat(),
        "card_count": sum(card.quantity for card in cards),
        "source_metadata": metadata.__dict__ if metadata else None,
    }

    if dry_run:
        return {"changed": True, "version": version, "hash": current_hash, "state": state}

    versions_dir = config.directory / "versions"
    versions_dir.mkdir(parents=True, exist_ok=True)
    config.directory.mkdir(parents=True, exist_ok=True)
    content = _header(config, retrieved_at, version, body, metadata) + body
    (versions_dir / f"{version}.txt").write_text(content, encoding="utf-8")
    (config.directory / "current.txt").write_text(content, encoding="utf-8")
    state_path.write_text(json.dumps(state, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    log_path = config.directory / "sync-log.md"
    log_entry = "\n".join(
        [
            f"## {version}",
            "",
            f"- Source: {config.url}",
            f"- Hash: `sha256:{current_hash}`",
            f"- Cards: {state['card_count']}",
            "",
        ]
    )
    if log_path.exists():
        log_path.write_text(log_path.read_text(encoding="utf-8") + log_entry, encoding="utf-8")
    else:
        log_path.write_text("# Synchronization log\n\n" + log_entry, encoding="utf-8")
    write_status(config, state)
    return {"changed": True, "version": version, "hash": current_hash, "state": state}
