slug = "shrine-bright-like-a-diamond"
display_name = "Shrine Bright Like a Diamond"
source = "archidekt"
url = "https://archidekt.com/decks/24922005/shrine_bright_like_a_diamond"
color_identity = "five-color"
